1. The table below shows the data about shoe size and height. Create a data frame.
```{r}
shoe_size <- c(6.5, 9.0, 8.5, 8.5, 10.5, 7.0, 9.5, 9.0, 13.0, 7.5, 10.5, 8.5, 12.0, 10.5, 13.0, 11.5, 8.5, 5.0, 10.0, 6.5, 7.5, 8.5, 10.5, 8.5, 10.5, 11.0, 9.0, 13.0)
height <-  c(66.0, 68.0, 64.5, 65.0, 70.0, 64.0, 70.0, 71.0, 72.0, 64.0, 74.5, 67.0, 71.0, 71.0, 77.0, 72.0, 59.0, 62.0, 72.0, 66.0, 64.0, 67.0, 73.0, 69.0, 72.0, 70.0, 69.0, 70.0)
gender <- c("F", "F", "F", "F", "M", "F", "F", "F", "M", "F", "M", "F", "M", "M", "M", "M", "F", "F", "M", "F", "F", "M", "M", "F", "M", "M", "M", "M")

frame1 <- data.frame(Shoesize = shoe_size, Height = height, Gender = gender)
frame1
```
b. Create a subset by males and females with their corresponding shoe size and height.
What its result? Show the R scripts.
```{r}
female <- subset(frame1, Gender == "F", select = c(Shoesize, Height))
female

male <- subset(frame1, Gender == "M", select = c(Shoesize, Height))
male
```
c. Find the mean of shoe size and height of the respondents. Write the R scripts and its result.
```{r}
meanshoe <- mean(frame1$Shoesize)
meanshoe

meanheight <- mean(frame1$Height)
meanheight
```
d. Is there a relationship between shoe size and height? Why?
```{r}
relation <- cor(frame1$Shoesize, frame1$Height)
relation
```

```{r}

```